name: Translate and Save

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  google:
    name: Google Translation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read Source File
        id: read-file
        run: |
          CONTENT=$(cat rules/en.md)
          echo "CONTENT<<EOF" >> $GITHUB_ENV
          echo "$CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - uses: fabasoad/translation-action@main
        id: google-step
        with:
          provider: google
          lang: en-lv
          source: ${{ env.CONTENT }}

      - name: Save Translated Content
        run: echo "${{ steps.google-step.outputs.text }}" > rules/lv.md

      - name: Commit and Push Translation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add rules/lv.md
          git commit -m "Add Latvian translation for rules"
          git push
