name: Translate and Save

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  google:
    name: Google Translation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: fabasoad/translation-action@main
        id: google-step
        with:
          provider: google
          lang: en-lv
          source: {{ github.workspace }}/rules/en.md

      - name: Save Translated Content
        run: echo "${{ steps.google-step.outputs.text }}" > rules/lv.md

      - name: Commit and Push Translation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add rules/lv.md
          git commit -m "Add Latvian translation for rules"
          git push
